export const Lines = [
    {
        id: 1,
        name: 'Line A',
        dailyTarget: 120,
        hourTarget: -10,
        actual: 50,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 85,
        morningTime: '08:00',
        afternoonTime: '13:00',
    },
    {
        id: 2,
        name: 'Line B',
        dailyTarget: 120,
        hourTarget: 12,
        actual: 100,
        isConnect: false,
        enable: true,
        is_Blink: true,
        performance: 70,
        morningTime: '08:30',
        afternoonTime: '13:30',
    },
    {
        id: 3,
        name: 'Line C',
        dailyTarget: 150,
        hourTarget: -15,
        actual: 75,
        isConnect: true,
        enable: false,
        is_Blink: false,
        performance: 50,
        morningTime: '09:00',
        afternoonTime: '14:00',
    },
    {
        id: 4,
        name: 'Line D',
        dailyTarget: 80,
        hourTarget: -8,
        actual: 40,
        isConnect: true,
        enable: true,
        is_Blink: true,
        performance: 95,
        morningTime: '08:15',
        afternoonTime: '13:15',
    },
    {
        id: 5,
        name: 'Line E',
        dailyTarget: 200,
        hourTarget: 20,
        actual: 180,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 90,
        morningTime: '08:45',
        afternoonTime: '13:45',
    },
    {
        id: 6,
        name: 'Line F',
        dailyTarget: 100,
        hourTarget: 10,
        actual: 30,
        isConnect: false,
        enable: true,
        is_Blink: true,
        performance: 45,
        morningTime: '07:30',
        afternoonTime: '12:30',
    },
    {
        id: 7,
        name: 'Line G',
        dailyTarget: 250,
        hourTarget: -25,
        actual: 200,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 80,
        morningTime: '09:15',
        afternoonTime: '14:15',
    },
    {
        id: 8,
        name: 'Line H',
        dailyTarget: 300,
        hourTarget: 30,
        actual: 250,
        isConnect: true,
        enable: false,
        is_Blink: false,
        performance: 85,
        morningTime: '08:10',
        afternoonTime: '13:10',
    },
    {
        id: 9,
        name: 'Line I',
        dailyTarget: 50,
        hourTarget: 5,
        actual: 25,
        isConnect: false,
        enable: false,
        is_Blink: true,
        performance: 60,
        morningTime: '07:45',
        afternoonTime: '12:45',
    },
    {
        id: 10,
        name: 'Line J',
        dailyTarget: 180,
        hourTarget: 18,
        actual: 170,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 95,
        morningTime: '09:00',
        afternoonTime: '14:00',
    },
    {
        id: 11,
        name: 'Line K',
        dailyTarget: 220,
        hourTarget: 22,
        actual: 190,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 85,
        morningTime: '08:50',
        afternoonTime: '13:50',
    },
    {
        id: 12,
        name: 'Line L',
        dailyTarget: 90,
        hourTarget: 9,
        actual: 60,
        isConnect: false,
        enable: false,
        is_Blink: true,
        performance: 55,
        morningTime: '07:40',
        afternoonTime: '12:40',
    },
    {
        id: 13,
        name: 'Line M',
        dailyTarget: 140,
        hourTarget: 14,
        actual: 100,
        isConnect: true,
        enable: true,
        is_Blink: true,
        performance: 75,
        morningTime: '09:20',
        afternoonTime: '14:20',
    },
    {
        id: 14,
        name: 'Line N',
        dailyTarget: 160,
        hourTarget: 16,
        actual: 110,
        isConnect: true,
        enable: false,
        is_Blink: false,
        performance: 65,
        morningTime: '08:25',
        afternoonTime: '13:25',
    },
    {
        id: 15,
        name: 'Line O',
        dailyTarget: 130,
        hourTarget: 13,
        actual: 120,
        isConnect: true,
        enable: true,
        is_Blink: false,
        performance: 90,
        morningTime: '09:05',
        afternoonTime: '14:05',
    },
];
